
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password: 8610425056aA@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 

 # Eureka Server URL*(In client Side We have to set True)

    fetch-registry: true  # Enable fetching registry from Eureka
    register-with-eureka: true  # Enable registering the service with Eureka
management:  
  tracing:  
    sampling:     
      probability: 1.0
      
